module.exports = {
    // Common
    INVALID_EMAIL_OR_PASSWORD: 'Invalid email or password',
    LOGIN_SUCCESS: 'Login successful',
    LOGOUT_SUCCESS: 'Logout successful',
    LOGOUT_FAILED: 'Logout failed',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    OTP_SENT: 'OTP sent to your email for verification.',
    OTP_INVALID: 'Invalid or expired OTP.',
    PASSWORD_UPDATED: 'Password updated successfully.',
    NO_TOKEN_PROVIDED: 'No token provided',
    UNAUTHORIZED: 'Unauthorized',
    FORBIDDEN_INVALID_ROLE: 'Forbidden: Invalid role',
    INVALID_TOKEN: 'Invalid token',
    PLEASE_AUTHENTICATE: 'Please authenticate.',
    // User
    USER_ALREADY_EXISTS: 'User already exists',
    USER_CREATED: 'User created successfully',
    USER_BLOCKED: 'Your account has been blocked. Please contact support.',
    USER_NOT_FOUND: 'User not found',
    EMAIL_ALREADY_EXISTS: 'Email already exists',
    FAILED_TO_UPDATE_PROFILE: 'Failed to update profile.',
    // Admin
    ADMIN_ALREADY_EXISTS: 'Admin with this email already exists',
    ADMIN_CREATED: 'Admin created successfully',
    ADMIN_NOT_FOUND: 'Admin not found',
    USER_BLOCKED: 'User blocked',
    USER_UNBLOCKED: 'User unblocked',
    USER_DELETED: 'User deleted successfully',
    CAPTAIN_BLOCKED: 'Captain blocked',
    CAPTAIN_UNBLOCKED: 'Captain unblocked',
    CAPTAIN_DELETED: 'Captain deleted successfully',
    CAPTAIN_NOT_FOUND: 'Captain not found',
    CAPTAIN_BLOCK_CONDITION: 'Captain cannot be blocked as they have completed less 3 rides ',
    FAILED_TO_DELETE_USER: 'Failed to delete user',
    FAILED_TO_DELETE_CAPTAIN: 'Failed to delete captain',
    FAILED_TO_FETCH_USERS: 'Failed to fetch users',
    FAILED_TO_FETCH_CAPTAINS: 'Failed to fetch captains',
    FAILED_TO_FETCH_RIDES: 'Failed to fetch rides',
    // Maps
    COORDINATES_NOT_FOUND: 'Coordinates not found',
    DISTANCE_TIME_NOT_FOUND: 'Distance and time not found',
    SUGGESTIONS_NOT_FOUND: 'Suggestions not found',
    // Ride
    RIDE_NOT_FOUND_OR_NOT_ACCEPTED: 'Ride not found or not in accepted state',
    RIDE_NOT_FOUND_OR_NOT_CANCELLABLE: 'Ride not found or not in cancellable state',
    RIDE_CANCELLED_BY_CAPTAIN: 'Ride cancelled by captain and user notified.',
    RIDE_CANCELLED_BY_USER: 'Ride cancelled by user and captain notified.',
    FAILED_TO_FETCH_USER_RIDE_HISTORY: 'Failed to fetch user ride history',
    FAILED_TO_FETCH_CAPTAIN_RIDE_HISTORY: 'Failed to fetch captain ride history'
};